language: python
python:
  - "2.7"
  - "3.5"
  - nightly

install:
  - pip install -e .
  - pip install --upgrade -r requirements-test.txt

script:
  - git --version
  - py.test tests/ --cov version --cov-report term-missing
